# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new version"
  lane :deploy do
    releaseFilePath = File.join(Dir.pwd, "key")
    gradle(
      task: "assemble",
      build_type: "Release",
      print_command: true,
      print_command_output: true,
      properties: {
        "android.injected.signing.store.file" => releaseFilePath,
        "android.injected.signing.store.password" => "123456",
        "android.injected.signing.key.alias" => "key0",
        "android.injected.signing.key.password" => "123456",
      }
    )
    copy_artifacts(
        artifacts: ['*/build/outputs/apk/**/*.apk'],
        target_path: File.join(Dir.pwd,"..","apk")
      )
  end
end
